/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_score_rahasak_utils_OpusDecoder */

#ifndef _Included_com_score_rahasak_utils_OpusDecoder
#define _Included_com_score_rahasak_utils_OpusDecoder
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_score_rahasak_utils_OpusDecoder_nativeInitDecoder
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jint JNICALL Java_com_score_rahasak_utils_OpusDecoder_nativeDecodeShorts
        (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

JNIEXPORT jint JNICALL Java_com_score_rahasak_utils_OpusDecoder_nativeDecodeBytes
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

JNIEXPORT jboolean JNICALL Java_com_score_rahasak_utils_OpusDecoder_nativeReleaseDecoder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

